apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-pod
spec:
  securityContext:
    runAsUser: 1000 #1000: default UID of jenkins user in default jnlp image
  containers:
    - name: maven3
      image: quay.io/snowdrop/ubi8-openjdk11-git
      command:
      - cat
      tty: true