apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      securityContext:
        runAsUser: 1000
      initContainers:
        - name: nss-wrapper
          image: localhost:5000/snowdrop/nss-wrapper
          command: ['sh', '-c', '/nss_wrapper.sh']
          env:
            - name: USER_NAME
              value: cloud
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share
      containers:
        - name: maven3
          image: registry.access.redhat.com/ubi8/openjdk-11 #localhost:5000/snowdrop/ubi8-openjdk11-git
          command:
          - cat
          tty: true
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share
      volumes:
        - name: shared-data
          emptyDir: { }