apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      securityContext:
        runAsUser: 1000710000
      containers:
        - name: maven3
          image: registry.access.redhat.com/ubi8/openjdk-11 #localhost:5000/snowdrop/ubi8-openjdk11-git
          command: ['sh', '-c']
          args:
            - sed -i 's/185/1000710000/g' passwd && cat
          tty: true
          volumeMounts:
            - name: shared-data
              mountPath: /tmp
      volumes:
        - name: shared-data
          emptyDir: { }