apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: maven3
          image: localhost:5000/snowdrop/ubi8-openjdk11-git
          command:
          - cat
          env:
           - name: LD_PRELOAD
             value: libnss_wrapper.so
           - name: NSS_WRAPPER_PASSWD
             value: /home/jboss/passwd
           - name: NSS_WRAPPER_GROUP
             value: /etc/group
          tty: true
          volumeMounts:
            - name: shared-data
              mountPath: /tmp
      volumes:
        - name: shared-data
          emptyDir: { }