apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      securityContext:
        runAsUser: 1000
      initContainers:
        - name: nss-wrapper
          image: localhost:5000/snowdrop/nss-wrapper:2
          command: ['sh', '-c', '/usr/local/bin/init.sh']
          env:
            - name: NSS_WRAPPER_PASSWD
              value: "/tmp/build.passwd"
            - name: NSS_WRAPPER_GROUP
              value: '/etc/group'
            - name: USER_NAME
              value: cloud
            - name: USER_DESCRIPTION
              value: Cloud
            - name: USER_HOME
              value: /home/cloud
          volumeMounts:
            - name: shared-data
              mountPath: /tmp
      containers:
        - name: maven3
          image: registry.access.redhat.com/ubi8/openjdk-11 #localhost:5000/snowdrop/ubi8-openjdk11-git
          command:
          - cat
          env:
           - name: LD_PRELOAD
             value: libnss_wrapper.so
           - name: NSS_WRAPPER_PASSWD
             value: /tmp/build.passwd
           - name: NSS_WRAPPER_GROUP
             value: /etc/group
          tty: true
          volumeMounts:
            - name: shared-data
              mountPath: /tmp
      volumes:
        - name: shared-data
          emptyDir: { }